apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${NAMESPACE}-${APP_NAME}-${ENV}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${CFG_REPO_URL}
    targetRevision: main
    path: kustomize/${APP_NAME}/overlays/${ENV}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
