## ___________________Usage___________________
# Use deploy for you ci app to set image tag
# Use DRY_RUN='' to disable dry run during deploy , use DRY_RUN='-o yaml' to view yamls that are created
#
CFG_REPO_URL  ?= https://github.com/viaacode/hetarchief-v3_k8s-resources.git # namespace apps
REPO_URL      ?= https://github.com/viaacode/hetarchief-client.git # code with dockerfile ...
SVC_PORT      ?= 5000
IMAGE_NAME    ?= $(shell echo "$(FINAL_NAME)" | sed -E 's@[@].*$$@@; s@:[^/]*$$@@')
DRY_RUN       ?= --dry-run=client # set optional kubectl options e.g. ='' to disable the dry run  ='-o yaml ' to view rendered yamls 
# defaults
APP_NAME      ?= demo
ENV           ?= int              # int | qas | prd
FINAL_NAME    ?= $(APP_NAME):latest
NAMESPACE     ?= meemoo-infra
ENVS          := int qas prd
REGISTRY_HOST ?= meeregistrymoo.azurecr.io


#PREFIX names

PREFIX        ?= $(NAMESPACE)
SUFFIX        ?= int

## configuration list of NAMESAPCE apps
APPS          := client proxy hasura
# App Metadata: Port and Source Code Repo
client_PORT      := 3000
client_REPO      := https://github.com/viaacode/hetarchief-client.git
client_CFG_REPO  := https://github.com/viaacode/hetarchief-v3_k8s-resources.git
proxy_PORT       := 5000
proxy_REPO       := https://github.com/viaacode/hetarchief-proxy.git
proxy_CFG_REPO   := https://github.com/viaacode/hetarchief-v3_k8s-resources.git
hasura_PORT      := 8080
hasura_REPO      := https://github.com/viaacode/hetarchief-hasura.git
hasura_CFG_REPO   := https://github.com/viaacode/hetarchief-v3_k8s-resources.git


.PHONY: build-all deploy-all-envs

# Example: Run your templator and kustomize build for every app
build-all:
	@$(foreach app, $(APPS), \
		echo "--- Processing $(app) ---"; \
		APP_NAME=$(app) \
		SVC_PORT=$($(app)_PORT) \
		REPO_URL=$($(app)_REPO) \
		SUFFIX=$${ENV} \
		$(MAKE) bootstrap; \
		$(MAKE) deploy-all-envs APP_NAME=$(app) SVC_PORT=$($(app)_PORT) REPO_URL=$($(app)_CFG_REPO); \
	)
	$(MAKE) deploy-all-envs
	$(MAKE) create_structure
	$(MAKE) generate-argocd
	@echo "All resources generated in k8s-resources/"
	tree k8s-resources

# Helper to run deploy for all envs this sets the tag to $ENV
deploy-all-envs:
	@for e in $(ENVS); do \
		ENV=$$e $(MAKE) deploy; \
	done

undeploy-all-apps:
	@for e in $(APPS); do \
                APP_NAME=$$e $(MAKE) undeploy; \
        done

.PHONY: generate-argocd
# This target generates the ArgoCD manifests for each app/env
generate-argocd:
	@echo "__creating ArgoCD manifests__"
	@mkdir -p k8s-resources/argocd/int k8s-resources/argocd/qas k8s-resources/argocd/prd
	@$(foreach env, $(ENVS), \
		ENV=$(env) envsubst < argocd-root-tmpl.yaml > k8s-resources/argocd/$(env)/root-app.yaml; \
		$(foreach app, $(APPS), \
			APP_NAME=$(app) ENV=$(env) envsubst < argocd-child-tmpl.yaml > k8s-resources/argocd/$(env)/$(app)-$(env).yaml; \
		) \
	)


create_structure:
	  @$(foreach app, $(APPS), \
                echo "Building $(app)..."; \
                mv $(app) k8s-resources/$(app); \
        )
push:
	git add k8s-resources/
	git commit -m "Deploying $(NAMESAPCE) stack: $(APPS)"
	git push origin main


export APP_NAME ENV FINAL_NAME NAMESPACE PREFIX SUFFIX CFG_REPO_URL

.PHONY: default bootstrap clean deploy int qas prd

# "make APP_NAME=my-app" → bootstrap
default: bootstrap

debug:
	echo $(IMAGE_NAME)

bootstrap:
	@echo "Bootstrapping app '$(APP_NAME)' with image '$(FINAL_NAME)' in namespace '$(NAMESPACE)'..."
	@mkdir -p "./$(APP_NAME)/base"
	@for e in $(ENVS); do \
		mkdir -p "./$(APP_NAME)/overlays/$$e"; \
	done

	@echo "__running generator.sh__"
	@./generator.sh

	@echo "__creating base kustomization__"
	@envsubst < kustomization-tmpl.yaml > "./$(APP_NAME)/base/kustomization.yaml"

	@echo "__creating overlay kustomizations (int/qas/prd)__"
	@for e in $(ENVS); do \
		SUFFIX=$$e ENV=$$e envsubst < kustomization-overlay-env-tmpl.yaml > "./$(APP_NAME)/overlays/$$e/kustomization.yaml"; \
	done

	@echo "__adding ExternalSecret manifests__"
	@for e in $(ENVS); do \
		ENV=$$e envsubst < externalsecret-tmpl.yaml > "./$(APP_NAME)/overlays/$$e/$(APP_NAME)-$$e-externalsecret.yaml"; \
                PREFIX=$(NAMESPACE) SUFFIX=$$e ENV=$$e envsubst < patch.yaml > "./$(APP_NAME)/overlays/$$e/patch-replica.yaml"; \
	done

	@echo "__adding app config env files__"
	@for e in $(ENVS); do \
		ENV=$$e envsubst < app_envfile-tmpl > "./$(APP_NAME)/overlays/$$e/$(APP_NAME)-config-$$e.env"; \
	done


	@echo "__adding per-env patches (resources + env/component labels + annotations)__"
	## split resources in more files


	@echo "__✅ created kustomize structure for $(APP_NAME)__"
	@echo "  - ./$(APP_NAME)/base"
	@echo "  - ./$(APP_NAME)/overlays/{int,qas,prd}"

clean:
	@echo "__🤟 removing $(APP_NAME) dir __"
	@rm -rf "./$(APP_NAME)"
	@echo "__✅ removed $(APP_NAME) dir __"
	@$(foreach app, $(APPS), \
                echo "__🤟 Deletinging $(app)..."; \
                rm -rf k8s-resources/$(app); \
        )
	@echo "__✅ removed $(APPS) dirs from k8s-resources/ __"


# Generic deploy uses ENV (int/qas/prd)
deploy:
	@echo "Deploying '$(APP_NAME)' to env '$(ENV)' with image '$(FINAL_NAME)'..."
	cd "./$(APP_NAME)/overlays/$(ENV)" &&  kustomize edit set image "$(FINAL_NAME)=$(REGISTRY_HOST)/$(NAMESPACE)/$(APP_NAME):$(ENV)" && \
  kubectl apply $(DRY_RUN) -k .

undeploy:
	kubectl delete -l app=$(APP_NAME)  svc,deploy,ing

# Convenience targets; ENV is set here and used in deploy + templates
int: ENV=int
int: deploy

qas: ENV=qas
qas: deploy

prd: ENV=prd
prd: deploy
